services:
  postgres:
    image: postgres:16.6-alpine
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_USER=user
      - POSTGRES_DB=postgresql

volumes:
    data:
