spring:
  application:
    name: honeycombs
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        auto_quote_keyword: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
        mail:
          smtp:
            auth: true
            starttls:
                enable: true

security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration-time: 3600000

server:
  error:
    include-message: always
  port: ${SERVER_PORT}

# Configuration replaced with logback-spring.xml
#logging:
#  level:
#    root: WARN
#    org.hibernate.SQL: DEBUG # allows to show SQL queries in the console
#    org.hibernate.orm.jdbc.bind: TRACE # allows to show bound values to `?` in the SQL queries
#  include-application-name: false
#  file:
#    path: logs
#  logback:
#    rollingpolicy:
#      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz

springdoc:
  api-docs:
    path: /api/docs

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always
